### PR TITLE
fix oneWayTls

### LINKED ISSUE #123: [Migrated] fix a few doc typos
Issue has been moved to https://github.com/k8sgateway/k8sgateway/issues/123

### PR DESCRIPTION
**Pull request by puertomontt**
# Description

envoy will still request a Client cert if validation context is set. This can cause an issue with some clients. In order to avoid requesting the client cert, set validation context to nil if one way tls is enabled.

Even though we set `RequireClientCertificate` to false, Envoy still _requests_ the cert if validation context is set. 

# Additional Notes

### CODE REVIEW

File: test/kubernetes/e2e/features/client_tls/suite.go [hunk 1]
```diff
@@ -50,6 +51,7 @@ func (s *clientTlsTestingSuite) TearDownSuite() {
 }
 
 func (s *clientTlsTestingSuite) TestRouteSecureRequestToUpstream() {
+	s.T().Skip("Skipping TestRouteSecureRequestToUpstream")
```
Comment (andy-fong) [inline test/kubernetes/e2e/features/client_tls/suite.go]: Can you put comment here and below on why the tests are skipped? or should they be removed?

Comment (puertomontt) [reply test/kubernetes/e2e/features/client_tls/suite.go]: accident

File: projects/gloo/pkg/utils/ssl_test.go [hunk 2]
```diff
@@ -233,6 +233,15 @@ Header: 1
 			Expect(cfg.RequireClientCertificate.GetValue()).To(BeFalse())
 		})
 
+		It("should remove validation context if oneWayTls enabled for downstream config", func() {
+			downstreamCfg.OneWayTls = &wrappers.BoolValue{Value: true}
+			cfg, err := configTranslator.ResolveDownstreamSslConfig(secrets, downstreamCfg)
+			Expect(err).NotTo(HaveOccurred())
+			// When oneWayTls is true, ValidationContext should be removed to prevent Envoy
+			// from requesting client certificates during the TLS handshake
+			Expect(cfg.CommonTlsContext.GetValidationContext()).To(BeNil(), "Validation context should be removed to prevent client certificate requests")
```
Comment (sheidkamp) [inline projects/gloo/pkg/utils/ssl_test.go:242]: Nit: this could have been combined with the test above, but the pattern in this file seems to be to keep the test cases separate like this. Don't need to update.

**Comment by fadecore** [comment]
Do you see any chance of a "workaround" based on configuration parameters for older versions?

**Comment by puertomontt** [comment]
> Do you see any chance of a "workaround" based on configuration parameters for older versions?

I don't think so. Which version?

**Comment by fadecore** [comment]
Currently we run 1.19.4, looking into release notes [v1.18.27](https://github.com/solo-io/gloo/releases/tag/v1.18.27) [v1.19.5](https://github.com/solo-io/gloo/releases/tag/v1.19.5) or [v1.20.8](https://github.com/solo-io/gloo/releases/tag/v1.20.8) would be the "minimum" versions to have this fix included.

**Comment by puertomontt** [comment]
@fadecore it has only been backported to 1.20.8. The other releases link to a different issue.

**Comment by fadecore** [comment]
You are correct, thanks for pointing out! 
Didn't read carefully, just looked for oneWayTls.
