### PR TITLE
[gateway2] Updates Gateway Controller Watch Predicate

### LINKED ISSUE #10099: Removing GatewayParameters Annotation from Gateway Does Not Propagate Updates
### Gloo Edge Product

Open Source

### Gloo Edge Version

1.17.7

### Kubernetes Version

v1.28.0

### Describe the bug

Initially adding the `gateway.gloo.solo.io/gateway-parameters-name: gloo-gateway2 ` annotation to the Gateway caused the managed proxy deployment replicas to be updated properly since gloo-gateway2 is configured with 2 replicas. Removing this annotation or updating the value to `gloo-gateway` (the default) does not cause the managed proxy deployment to revert back to 1 unless I reboot GG.

### Expected Behavior

The managed proxy deployment to be updated with 1 replica.

### Steps to reproduce the bug

1. Setup GGv2 using the quick start [guide](https://docs.solo.io/gateway/latest/quickstart/).
2. Create a new GatewayParameters with all the same configuration as the default GatewayParameters except change replicas from 1 to 2.
3. Update the Gateway to reference the new GatewayParameters by applying the `gateway.gloo.solo.io/gateway-parameters-name` annotation.
4. Observe the number of replicas for the managed Envoy deployment.
5. Remove the the annotation.
6. Observe the number of replicas for the managed Envoy deployment.

### Additional Environment Detail

I used the `ci/kind/setup-kind.sh` script to setup the cluster, load gloo images, etc.

### Additional Context

_No response_

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1207635280052738/1208391610128313) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by danehans**
Previously, the controller would only watch Gateway objects for `generation` field changes which is not updated when annotations change. Since Gateway reconciliation should be triggered when the `gateway.gloo.solo.io/gateway-parameters-name` annotation is added, removed, or modified, the predicate was updated to check for changes in either the generation field or the annotations.

Fixes #10099

BOT NOTES: 
resolves https://github.com/solo-io/gloo/issues/10099

### CODE REVIEW

File: projects/gateway2/controller/controller.go [hunk 1]
```diff
@@ -176,15 +177,50 @@ func (c *controllerBuilder) watchGw(ctx context.Context) error {
...
+					return true
+				}
+			}
+
+			// Check for any new keys that exist in the new annotations but not in the old
+			for key := range newAnnotations {
+				if _, exists := oldAnnotations[key]; !exists {
+					return true
+				}
+			}
```
Comment (EItanya) [inline projects/gateway2/controller/controller.go:208]: https://pkg.go.dev/maps#Equal

**Review by timflannagan — APPROVED** [review]

File: projects/gateway2/controller/controller.go [hunk 2]
```diff
@@ -176,15 +178,31 @@ func (c *controllerBuilder) watchGw(ctx context.Context) error {
 		return err
 	}
 
-	buildr := ctrl.NewControllerManagedBy(c.cfg.Mgr).
-		// Don't use WithEventFilter here as it also filters events for Owned objects.
-		For(&apiv1.Gateway{}, builder.WithPredicates(predicate.NewPredicateFuncs(func(object client.Object) bool {
+	pred := predicate.Funcs{
+		UpdateFunc: func(e event.UpdateEvent) bool {
+			// Check for generation change
```
Comment (jenshu) [inline projects/gateway2/controller/controller.go:183]: looks like there is an AnnotationChangedPredicate; can we do something like [this](https://github.com/kubernetes-sigs/controller-runtime/blob/236e448db12c423c16c31485a8ef20313a6880da/pkg/predicate/predicate.go#L230)?

Comment (danehans) [reply projects/gateway2/controller/controller.go:183]: Good catch @jenshu! I'll update the PR accordingly.

Comment (danehans) [reply projects/gateway2/controller/controller.go]: Commit https://github.com/solo-io/gloo/commit/f3d37ef4a35124987f87e3dffa278c12c1213ae0 resolves this comment.

File: test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go [hunk 3]
```diff
@@ -33,12 +33,17 @@ func NewMinimalDefaultGatewayParametersTestingSuite(ctx context.Context, testIns
 
 func (s *minimalDefaultGatewayParametersDeployerSuite) TestConfigureProxiesFromGatewayParameters() {
 	s.T().Cleanup(func() {
-		err := s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwParametersManifestFile)
+		err := s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwWithParametersManifestFile)
 		s.NoError(err, "can delete basic gateway manifest")
-		s.testInstallation.Assertions.EventuallyObjectsNotExist(s.ctx, gwParams, proxyService, proxyDeployment)
+		err = s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwParamsManifestFile)
+		s.NoError(err, "can delete manifest")
+		s.testInstallation.Assertions.EventuallyObjectsNotExist(s.ctx, gwParams)
```
Comment (jenshu) [inline test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go:40]: maybe a merge issue but can this line be deleted since we also check gwParams below?

File: test/kubernetes/e2e/features/deployer/suite.go [hunk 4]
```diff
@@ -58,10 +58,18 @@ func (s *testingSuite) TestProvisionDeploymentAndService() {
...
+		err := s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwWithParametersManifestFile)
+		s.NoError(err, "can delete manifest")
+		s.testInstallation.Assertions.EventuallyObjectsNotExist(s.ctx, gtw)
+
+		err = s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwParamsManifestFile)
 		s.NoError(err, "can delete manifest")
 		s.testInstallation.Assertions.EventuallyObjectsNotExist(s.ctx, gwParams)
 
+		err = s.testInstallation.Actions.Kubectl().DeleteFile(s.ctx, gwParamsCustomManifestFile)
+		s.NoError(err, "can delete manifest")
```
Comment (jenshu) [inline test/kubernetes/e2e/features/deployer/suite.go:70]: nit: can all the `NoError` have different error messages (e.g. append the manifest filename)?

**Review by jenshu — APPROVED** [review]

File: changelog/v1.18.0-beta23/gateway2-gateway-controller-watch-annotations.yaml [hunk 5]
```diff
@@ -0,0 +1,10 @@
+changelog:
```
Comment (jenshu) [inline changelog/v1.18.0-beta23/gateway2-gateway-controller-watch-annotations.yaml:1]: need to move changelog to beta24

Comment (danehans) [reply changelog/v1.18.0-beta23/gateway2-gateway-controller-watch-annotations.yaml]: Commit https://github.com/solo-io/gloo/commit/e1f1df9e7db81d7de51bbefe4a87e9d502ea8fae resolves this comment.

File: test/kubernetes/e2e/features/deployer/suite.go (hunk 4 above)
Comment (danehans) [reply test/kubernetes/e2e/features/deployer/suite.go]: Commit https://github.com/solo-io/gloo/commit/e1f1df9e7db81d7de51bbefe4a87e9d502ea8fae resolves this comment.

File: test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go (hunk 3 above)
Comment (danehans) [reply test/kubernetes/e2e/features/deployer/minimal_default_gatewayparameters_deployer_suite.go]: Commit https://github.com/solo-io/gloo/commit/e1f1df9e7db81d7de51bbefe4a87e9d502ea8fae resolves this comment.

**Review by timflannagan — APPROVED** [review]

**Review by timflannagan — APPROVED** [review]

**Review by jenshu — APPROVED** [review]
